[2024-03-05 18:13:55,967][jax._src.profiler][INFO] - Loading trace.json.gz and removing its metadata...
[2024-03-05 18:13:57,216][jax._src.profiler][INFO] - Writing perfetto_trace.json.gz...
Exception ignored in: <function _xla_gc_callback at 0x102e77ee0>
Traceback (most recent call last):
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 97, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x102e77ee0>
Traceback (most recent call last):
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 97, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Open URL in browser: https://ui.perfetto.dev/#!/?url=http://127.0.0.1:9001/perfetto_trace.json.gz
127.0.0.1 - - [05/Mar/2024 18:14:08] code 404, message File not found
127.0.0.1 - - [05/Mar/2024 18:14:08] "POST /status HTTP/1.1" 404 -
127.0.0.1 - - [05/Mar/2024 18:14:08] "GET /perfetto_trace.json.gz HTTP/1.1" 200 -
Error executing job with overrides: []
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/benjamin/code/signification-game/base_experiment/ippo_ff.py", line 549, in main
    out = train(rng)
  File "/Users/benjamin/code/signification-game/base_experiment/ippo_ff.py", line 507, in train
    runner_state, traj_batch = jax.lax.scan( # Perform the update step for a specified number of updates and update the runner state
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Generated function failed: CpuCallback error: KeyboardInterrupt: <EMPTY MESSAGE>
At:
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/interpreters/mlir.py(2366): _wrapped_callback
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py(1151): __call__
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/profiler.py(336): wrapper
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/pjit.py(1185): _pjit_call_impl_python
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/pjit.py(1229): call_impl_cache_miss
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/pjit.py(1245): _pjit_call_impl
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/core.py(935): process_primitive
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/core.py(447): bind_with_trace
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/core.py(2740): bind
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/pjit.py(168): _python_pjit_helper
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/pjit.py(257): cache_miss
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/traceback_util.py(179): reraise_with_filtered_traceback
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/dispatch.py(87): apply_primitive
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/core.py(935): process_primitive
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/core.py(447): bind_with_trace
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/core.py(2740): bind
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py(1130): scan_bind
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py(273): scan
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/jax/_src/traceback_util.py(179): reraise_with_filtered_traceback
  /Users/benjamin/code/signification-game/base_experiment/ippo_ff.py(507): train
  /Users/benjamin/code/signification-game/base_experiment/ippo_ff.py(549): main
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/hydra/core/utils.py(186): run_job
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/hydra/_internal/hydra.py(119): run
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/hydra/_internal/utils.py(458): <lambda>
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/hydra/_internal/utils.py(220): run_and_report
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/hydra/_internal/utils.py(457): _run_app
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/hydra/_internal/utils.py(394): _run_hydra
  /Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/hydra/main.py(94): decorated_main
  /Users/benjamin/code/signification-game/base_experiment/ippo_ff.py(554): <module>
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.